name: SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarQube:
    name: Run SonarQube Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarQube Scan via Docker
        env:
          SONAR_TOKEN: "sqa_0cf40b5569721717150fe19a8195bdfc360b6107"
          SONAR_HOST_URL: "http://34.72.82.154:9000"
          SONAR_PROJECT_KEY: "Watermelons_SOEN390"
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=${SONAR_HOST_URL} \
            -e SONAR_LOGIN=${SONAR_TOKEN} \
            -v "${GITHUB_WORKSPACE}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.sources=.
