name: SonarQube Analysis

on: [push, pull_request]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: "sqa_0cf40b5569721717150fe19a8195bdfc360b6107"
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Watermelons_SOEN390 \
            -Dsonar.host.url=http://34.72.82.154:9000 \
            -Dsonar.login="sqa_0cf40b5569721717150fe19a8195bdfc360b6107\
            -Dsonar.ws.timeout=60
